baseURL = "https://bbrks.me/"
languageCode = "en-gb"
title = "Ben Brooks"
theme = "gruvbox"
sectionPagesMenu = "sections"
paginate = 5
disqusShortname = "bbrks"

[permalinks]
  posts = "/:slug"

[markup.goldmark.renderer]
  unsafe= true

[params]
  author = { name = "Ben Brooks" }
  description = "Software Engineer & Gopher"
  keywords = ["software engineering", "golang", "gopher", "blog", "programmer", "bbrks"]
  titlePrefix = ""
  titleSuffix = " | bbrks.me"
  dateFormat = "2006-01-02"
  menuItemPrefix = "~/"
  postTruncateLength = 250
  disqusAutoLoad = false
  disqusAutoLoadCount = false
  logo = "dalle-avatar-1-bbrks.png"

[[menu.social]]
  name = "Mastodon"
  url = "https://mstdn.io/@bbrks"
  weight = 1
  [menu.social.params]
    rel = 'me'
[[menu.social]]
  name = "GitHub"
  url = "https://github.com/bbrks"
  weight = 10
[[menu.social]]
  name = "LinkedIn"
  url = "https://uk.linkedin.com/in/bbrks"
  weight = 100
